Event Model and Spec (#EV-04)
Snehithlal/Eventy pull request #11
Opened 2021-07-17 17:36 UTC by Snehithlal

2021-07-17 18:37 UTC, anbk77 requested changes

2021-07-17 18:37 UTC, anbk77 commented on app/controllers/api/v1/events_controller.rb
> +            event: EventSerializer.render_as_json(event) }, status: :unprocessable_entity
@Snehithlal why do we need event serializer here?

2021-07-17 18:37 UTC, anbk77 commented on app/controllers/api/v1/events_controller.rb
> +          render json: { event: EventSerializer.render_as_json(event, view: :with_all_associations) }, status: :created
@Snehithlal can refactor as ` json:  EventSerializer.render_as_json(event, root: :event, view: :with_all_associations)`

2021-07-17 18:42 UTC, anbk77 approved these changes

2021-07-17 18:43 UTC, anbk77 approved these changes

2021-07-17 18:43 UTC, commonman007 approved these changes

2021-07-17 18:43 UTC, merged

2021-07-18 06:38 UTC, Snehithlal commented
![](https://github.trello.services/images/mini-trello-icon.png) [[EV-04] Event creation Api](https://trello.com/c/0itqbYMg/7-ev-04-event-creation-api)